### ISSUE TITLE
translations

### ISSUE THREAD

**Issue by dextel2** [dextel2/core-server#11]
So all of the text in the app is currently statically English, however, if someone changes languages to let's say french then the text should change to french. refer to the [i18next](https://www.npmjs.com/package/i18n) package for the same.

Currently, only two languages are required i.e. English and French

**Comment by STM3900** [comment]
Asign me, i will do that

**Comment by dextel2** [comment]
Done, Work in the develop branch and when done make PR to the develop branch only!

**Comment by STM3900** [comment]
I have a question : 
I noticed that you don't have i18n package installed, should i have to install it ? (it might be a bad idea because i don't know your ecosystem very well)

**Comment by dextel2** [comment]
> I have a question : I noticed that you don't have i18n package installed, should i have to install it ? (it might be a bad idea because i don't know your ecosystem very well)

Yes, install it, not a problem.

**Comment by STM3900** [comment]
Okay, I'll let you know if I have a problem

**Comment by STM3900** [comment]
I am having trouble getting i18n to work and I am afraid of damaging your project. Is it ok if I make a json file that contains the translations without having to install i18n?

**Comment by dextel2** [comment]
> I am having trouble getting i18n to work and I am afraid of damaging your project. Is it ok if I make a json file that contains the translations without having to install i18n?

Okay

**Comment by STM3900** [comment]
Done!

**Comment by dextel2** [comment]
@STM3900 what issues did you face with i18n?

**Comment by STM3900** [comment]
I'm not used with your code ecosystem, and i didn't want to break something

**Comment by dextel2** [comment]
Stale issue message
