### ISSUE TITLE
Create README

### ISSUE THREAD

**Issue by dextel2** [dextel2/core-server#9]
Need help to write a good README file!

**Comment by nkhandelwal07** [comment]
I can help! What do you want on the file?

**Comment by dextel2** [comment]
Okay! Make sure you work in the develop branch and generate PR for that branch only

**Comment by dextel2** [comment]
@nkhandelwal07 I want a basic write down regarding this project which includes

1. This is a boilerplate project, meaning anyone can use this as a template
2. This is a build upon MySQL and MongoDB so you have the choice to build your project using this template
3. The UI is very simple and the idea is to use CRUD operations in proper way

**Comment by nkhandelwal07** [comment]
ok. I can't do it now, but I can start tomorrow. If  you want it earlier, feel free to assign it to someone else, sorry about that!

**Comment by dextel2** [comment]
> ok. I can't do it now, but I can start tomorrow. If you want it earlier, feel free to assign it to someone else, sorry about that!

at your own pace! :+1:

**Comment by nkhandelwal07** [comment]
Is there a certain feature you want?

**Comment by dextel2** [comment]
> Is there a certain feature you want?

No nothing specific, but if you add that good looking feel to the README, that'd be great!

**Comment by dextel2** [comment]
Stale issue message
